require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/IndentationStyle:
  EnforcedStyle: spaces
Layout/LineLength:
  Max: 120

Lint/MissingSuper:
  Enabled: false
Lint/ScriptPermission:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Naming/MethodParameterName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - "spec/**/*"
Style/MultilineIfModifier:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false


RSpec/ContextWording:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/ReceiveCounts:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
